services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    command: >
      sh -c "
      docker-entrypoint.sh postgres &
      sleep 10 &&
      psql -v ON_ERROR_STOP=1 --username "$$POSTGRES_USER" --dbname "$$POSTGRES_DB" <<-EOSQL
          CREATE DATABASE postgres_test;
      EOSQL
      "  
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data  


  minio:
    container_name: "minio"
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z-cpuv1
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - custom

  meme_app:
    container_name: "meme_app"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - minio
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge
volumes:
  db-data: